name: Check for Game updates

on:
  schedule:
    # every day at 5:45 PM UTC (should be decently after beatgames usually releases their game)
    - cron: '45 17 * * *'
  workflow_dispatch:
  push:
    branches:
      - 'master'
      - 'feat/auto-generation'
    paths:
      - '.github/actions/app-update/*'
      - '.github/actions/cordl-run/*'
      - '.github/workflows/check-for-updates.yml'
      - 'scripts/deno/*'
      - 'lastversion.txt'

env:
  CORDL_GIT: "https://github.com/Fernthedev/cordl"
  CORDL_BRANCH: "dev/generic_methods_redo"

jobs:
  update-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Get QPM
        if: steps.cache-qpm.outputs.cache-hit != 'true'
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: cargo-build.yml
          name: linux-qpm
          path: QPM
          repo: QuestPackageManager/QPM.CLI

      - name: Put QPM on path
        run: |
          chmod +x ./QPM/qpm
          echo "${GITHUB_WORKSPACE}/QPM" >> $GITHUB_PATH

      - name: Check for app updates
        uses: ./.github/actions/app-update
        id: version-check
        with:
          oculus-token: ${{ secrets.OCULUS_TOKEN }}
          last-version-file: "${GITHUB_WORKSPACE}/lastversion.txt"

      - name: Run cordl
        if: ${{ steps.version-check.outputs.update-available }}
        id: cordl-run
        uses: ./.github/actions/cordl-run
        with:
          cordl-git: ${{env.CORDL_GIT}}
          cordl-branch: ${{env.CORDL_BRANCH}}
          libil2cpp-path: "${GITHUB_WORKSPACE}/output/libil2cpp.so"
          metadata-path: "${GITHUB_WORKSPACE}/output/libil2cpp.so"
          format: true

      - name: Move files
        if: ${{ steps.version-check.outputs.update-available }}
        run: |
          rm -rf ${GITHUB_WORKSPACE}/include
          mv ${{ steps.cordl-run.outputs.include-path }} ${GITHUB_WORKSPACE}/include

      - name: Configure commit
        if: ${{ steps.version-check.outputs.update-available }}
        run: |
          git config user.name "Github Actions"
          git config user.email "<>"
          git checkout -b test-${{ steps.version-check.outputs.new-version }}
      # we checkout a new branch so that we can test multiple times instead of having to delete commits from a used branch

      # last version file is pushed before anything else, and to the main branch of the repo
      - name: Commit and push new lastversion file
        if: ${{ steps.version-check.outputs.update-available }}
        env:
          OLD_VERSION: ${{ steps.version-check.outputs.old-version }}
          NEW_VERSION: ${{ steps.version-check.outputs.new-version }}
        run: |
          git add lastversion.txt
          git commit -m "Last version $OLD_VERSION -> $NEW_VERSION" --allow-empty
          git push

      - name: Bump package minor version
        if: ${{ steps.version-check.outputs.update-available }}
        run: deno run --allow-run --allow-read ./scripts/deno/bump.ts

      # updated qpm info also needs to go to the main branch to work correctly
      - name: Update QPM info
        if: ${{ steps.version-check.outputs.update-available }}
        run: |
          qpm package edit-extra --branchName "$TARGET_BRANCH"
          qpm restore
          git add qpm.json qpm.shared.json
          git commit -m "Update Package version and info" --allow-empty
          git push

      # header files go to a seperate branch unrelated to the main one
      - name: Commit and push new header files to seperate branch
        if: ${{ steps.version-check.outputs.update-available }}
        env:
          OLD_VERSION: ${{ steps.version-check.outputs.old-version }}
          NEW_VERSION: ${{ steps.version-check.outputs.new-version }}
          TARGET_BRANCH: "update/bs-${{ steps.version-check.outputs.new-version }}"
        run: |
          git add ./include
          git commit -m "Update headers from $OLD_VERSION -> $NEW_VERSION" --allow-empty
          git push -u origin $TARGET_BRANCH

      - name: Get Commit ID
        if: ${{ steps.version-check.outputs.update-available }}
        id: commit-id
        run: |
          echo `git rev-parse HEAD`
          echo ::set-output name=ID::`git rev-parse HEAD`

      - name: Get QPM info
        if: ${{ steps.version-check.outputs.update-available }}
        id: qpm-info
        uses: RedBrumbler/qpm-info@main

      - name: Create release
        if: ${{ steps.version-check.outputs.update-available }}
        uses: ncipollo/release-action@v1
        with:
          commit: ${{ steps.commit-id.outputs.ID }}
          tag: "v${{ steps.qpm-info.outputs.version}}"
          name: "Update for ${{ steps.version-check.outputs.new-version }}"
          body: "Update from game version ${{ steps.version-check.outputs.old-version }} -> ${{ steps.version-check.outputs.new-version }}"
